<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TRSF.Invoicing.Catalogs.Sqlite</RootNamespace>
    <AssemblyName>TRSF.Invoicing.Catalogs.Sqlite</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TRSF.Invoicing\TRSF.Invoicing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\catalogs.sqlite">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
