//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRSF.Invoicing.srvSeguridad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaServicio", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallaSesion", Namespace="http://Ecodex.WS.Model/2011/CFDI")]
    [System.SerializableAttribute()]
    public partial class FallaSesion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", ConfigurationName="srvSeguridad.Seguridad")]
    public interface Seguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerToken", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRSF.Invoicing.srvSeguridad.FallaServicio), Action="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerTokenFallaServicioFault", Name="FallaServicio")]
        [System.ServiceModel.FaultContractAttribute(typeof(TRSF.Invoicing.srvSeguridad.FallaSesion), Action="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerTokenFallaSesionFault", Name="FallaSesion")]
        TRSF.Invoicing.srvSeguridad.RespuestaObtenerToken ObtenerToken(TRSF.Invoicing.srvSeguridad.SolicitudObtenerToken request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerToken", ReplyAction="http://Ecodex.WS.Model/2011/CFDI/Seguridad/ObtenerTokenResponse")]
        System.Threading.Tasks.Task<TRSF.Invoicing.srvSeguridad.RespuestaObtenerToken> ObtenerTokenAsync(TRSF.Invoicing.srvSeguridad.SolicitudObtenerToken request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitudObtenerToken", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class SolicitudObtenerToken {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionID;
        
        public SolicitudObtenerToken() {
        }
        
        public SolicitudObtenerToken(string RFC, long TransaccionID) {
            this.RFC = RFC;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RespuestaObtenerToken", WrapperNamespace="http://Ecodex.WS.Model/2011/CFDI", IsWrapped=true)]
    public partial class RespuestaObtenerToken {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=0)]
        public string Token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ecodex.WS.Model/2011/CFDI", Order=1)]
        public long TransaccionID;
        
        public RespuestaObtenerToken() {
        }
        
        public RespuestaObtenerToken(string Token, long TransaccionID) {
            this.Token = Token;
            this.TransaccionID = TransaccionID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeguridadChannel : TRSF.Invoicing.srvSeguridad.Seguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadClient : System.ServiceModel.ClientBase<TRSF.Invoicing.srvSeguridad.Seguridad>, TRSF.Invoicing.srvSeguridad.Seguridad {
        
        public SeguridadClient() {
        }

        public SeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TRSF.Invoicing.srvSeguridad.RespuestaObtenerToken TRSF.Invoicing.srvSeguridad.Seguridad.ObtenerToken(TRSF.Invoicing.srvSeguridad.SolicitudObtenerToken request) {
            return base.Channel.ObtenerToken(request);
        }
        
        public string ObtenerToken(string RFC, ref long TransaccionID) {
            TRSF.Invoicing.srvSeguridad.SolicitudObtenerToken inValue = new TRSF.Invoicing.srvSeguridad.SolicitudObtenerToken();
            inValue.RFC = RFC;
            inValue.TransaccionID = TransaccionID;
            TRSF.Invoicing.srvSeguridad.RespuestaObtenerToken retVal = ((TRSF.Invoicing.srvSeguridad.Seguridad)(this)).ObtenerToken(inValue);
            TransaccionID = retVal.TransaccionID;
            return retVal.Token;
        }
        
        public System.Threading.Tasks.Task<TRSF.Invoicing.srvSeguridad.RespuestaObtenerToken> ObtenerTokenAsync(TRSF.Invoicing.srvSeguridad.SolicitudObtenerToken request) {
            return base.Channel.ObtenerTokenAsync(request);
        }
    }
}
