<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TRSF.Invoicing.PDF</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="7.2.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TRSF.Invoicing\TRSF.Invoicing.csproj" />
  </ItemGroup>

</Project>
