<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:catCFDI="http://www.sat.gob.mx/sitio_internet/cfd/catalogos" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sat.gob.mx/sitio_internet/cfd/catalogos" elementFormDefault="unqualified" attributeFormDefault="unqualified">
<xs:simpleType name="c_FormaPago">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="01"/>
			<xs:enumeration value="02"/>
			<xs:enumeration value="03"/>
			<xs:enumeration value="04"/>
			<xs:enumeration value="05"/>
			<xs:enumeration value="06"/>
			<xs:enumeration value="08"/>
			<xs:enumeration value="12"/>
			<xs:enumeration value="13"/>
			<xs:enumeration value="14"/>
			<xs:enumeration value="15"/>
			<xs:enumeration value="17"/>
			<xs:enumeration value="23"/>
			<xs:enumeration value="24"/>
			<xs:enumeration value="25"/>
			<xs:enumeration value="26"/>
			<xs:enumeration value="27"/>
			<xs:enumeration value="28"/>
			<xs:enumeration value="29"/>
			<xs:enumeration value="30"/>
			<xs:enumeration value="31"/>
			<xs:enumeration value="99"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_Moneda">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="AED"/>
			<xs:enumeration value="AFN"/>
			<xs:enumeration value="ALL"/>
			<xs:enumeration value="AMD"/>
			<xs:enumeration value="ANG"/>
			<xs:enumeration value="AOA"/>
			<xs:enumeration value="ARS"/>
			<xs:enumeration value="AUD"/>
			<xs:enumeration value="AWG"/>
			<xs:enumeration value="AZN"/>
			<xs:enumeration value="BAM"/>
			<xs:enumeration value="BBD"/>
			<xs:enumeration value="BDT"/>
			<xs:enumeration value="BGN"/>
			<xs:enumeration value="BHD"/>
			<xs:enumeration value="BIF"/>
			<xs:enumeration value="BMD"/>
			<xs:enumeration value="BND"/>
			<xs:enumeration value="BOB"/>
			<xs:enumeration value="BOV"/>
			<xs:enumeration value="BRL"/>
			<xs:enumeration value="BSD"/>
			<xs:enumeration value="BTN"/>
			<xs:enumeration value="BWP"/>
			<xs:enumeration value="BYR"/>
			<xs:enumeration value="BZD"/>
			<xs:enumeration value="CAD"/>
			<xs:enumeration value="CDF"/>
			<xs:enumeration value="CHE"/>
			<xs:enumeration value="CHF"/>
			<xs:enumeration value="CHW"/>
			<xs:enumeration value="CLF"/>
			<xs:enumeration value="CLP"/>
			<xs:enumeration value="CNH"/>
			<xs:enumeration value="CNY"/>
			<xs:enumeration value="COP"/>
			<xs:enumeration value="COU"/>
			<xs:enumeration value="CRC"/>
			<xs:enumeration value="CUC"/>
			<xs:enumeration value="CUP"/>
			<xs:enumeration value="CVE"/>
			<xs:enumeration value="CZK"/>
			<xs:enumeration value="DJF"/>
			<xs:enumeration value="DKK"/>
			<xs:enumeration value="DOP"/>
			<xs:enumeration value="DZD"/>
			<xs:enumeration value="EGP"/>
			<xs:enumeration value="ERN"/>
			<xs:enumeration value="ESD"/>
			<xs:enumeration value="ETB"/>
			<xs:enumeration value="EUR"/>
			<xs:enumeration value="FJD"/>
			<xs:enumeration value="FKP"/>
			<xs:enumeration value="GBP"/>
			<xs:enumeration value="GEL"/>
			<xs:enumeration value="GHS"/>
			<xs:enumeration value="GIP"/>
			<xs:enumeration value="GMD"/>
			<xs:enumeration value="GNF"/>
			<xs:enumeration value="GTQ"/>
			<xs:enumeration value="GYD"/>
			<xs:enumeration value="HKD"/>
			<xs:enumeration value="HNL"/>
			<xs:enumeration value="HRK"/>
			<xs:enumeration value="HTG"/>
			<xs:enumeration value="HUF"/>
			<xs:enumeration value="IDR"/>
			<xs:enumeration value="ILS"/>
			<xs:enumeration value="INR"/>
			<xs:enumeration value="IQD"/>
			<xs:enumeration value="IRR"/>
			<xs:enumeration value="ISK"/>
			<xs:enumeration value="JMD"/>
			<xs:enumeration value="JOD"/>
			<xs:enumeration value="JPY"/>
			<xs:enumeration value="KES"/>
			<xs:enumeration value="KGS"/>
			<xs:enumeration value="KHR"/>
			<xs:enumeration value="KMF"/>
			<xs:enumeration value="KPW"/>
			<xs:enumeration value="KRW"/>
			<xs:enumeration value="KWD"/>
			<xs:enumeration value="KYD"/>
			<xs:enumeration value="KZT"/>
			<xs:enumeration value="LAK"/>
			<xs:enumeration value="LBP"/>
			<xs:enumeration value="LKR"/>
			<xs:enumeration value="LRD"/>
			<xs:enumeration value="LSL"/>
			<xs:enumeration value="LYD"/>
			<xs:enumeration value="MAD"/>
			<xs:enumeration value="MDL"/>
			<xs:enumeration value="MGA"/>
			<xs:enumeration value="MKD"/>
			<xs:enumeration value="MMK"/>
			<xs:enumeration value="MNT"/>
			<xs:enumeration value="MOP"/>
			<xs:enumeration value="MRO"/>
			<xs:enumeration value="MUR"/>
			<xs:enumeration value="MVR"/>
			<xs:enumeration value="MWK"/>
			<xs:enumeration value="MXN"/>
			<xs:enumeration value="MXV"/>
			<xs:enumeration value="MYR"/>
			<xs:enumeration value="MZN"/>
			<xs:enumeration value="NAD"/>
			<xs:enumeration value="NGN"/>
			<xs:enumeration value="NIC"/>
			<xs:enumeration value="NIO"/>
			<xs:enumeration value="NOK"/>
			<xs:enumeration value="NPR"/>
			<xs:enumeration value="NZD"/>
			<xs:enumeration value="OMR"/>
			<xs:enumeration value="PAB"/>
			<xs:enumeration value="PEN"/>
			<xs:enumeration value="PGK"/>
			<xs:enumeration value="PHP"/>
			<xs:enumeration value="PKR"/>
			<xs:enumeration value="PLN"/>
			<xs:enumeration value="PYG"/>
			<xs:enumeration value="QAR"/>
			<xs:enumeration value="RON"/>
			<xs:enumeration value="RSD"/>
			<xs:enumeration value="RUB"/>
			<xs:enumeration value="RWF"/>
			<xs:enumeration value="SAR"/>
			<xs:enumeration value="SBD"/>
			<xs:enumeration value="SCR"/>
			<xs:enumeration value="SDG"/>
			<xs:enumeration value="SEK"/>
			<xs:enumeration value="SGD"/>
			<xs:enumeration value="SHP"/>
			<xs:enumeration value="SLL"/>
			<xs:enumeration value="SOS"/>
			<xs:enumeration value="SRD"/>
			<xs:enumeration value="SSP"/>
			<xs:enumeration value="STD"/>
			<xs:enumeration value="SVC"/>
			<xs:enumeration value="SYP"/>
			<xs:enumeration value="SZL"/>
			<xs:enumeration value="THB"/>
			<xs:enumeration value="TJS"/>
			<xs:enumeration value="TMT"/>
			<xs:enumeration value="TND"/>
			<xs:enumeration value="TOP"/>
			<xs:enumeration value="TRY"/>
			<xs:enumeration value="TTD"/>
			<xs:enumeration value="TWD"/>
			<xs:enumeration value="TZS"/>
			<xs:enumeration value="UAH"/>
			<xs:enumeration value="UGX"/>
			<xs:enumeration value="USD"/>
			<xs:enumeration value="USN"/>
			<xs:enumeration value="UYI"/>
			<xs:enumeration value="UYP"/>
			<xs:enumeration value="UYU"/>
			<xs:enumeration value="UZS"/>
			<xs:enumeration value="VEF"/>
			<xs:enumeration value="VES"/>
			<xs:enumeration value="VND"/>
			<xs:enumeration value="VUV"/>
			<xs:enumeration value="WST"/>
			<xs:enumeration value="XAF"/>
			<xs:enumeration value="XAG"/>
			<xs:enumeration value="XAU"/>
			<xs:enumeration value="XBA"/>
			<xs:enumeration value="XBB"/>
			<xs:enumeration value="XBC"/>
			<xs:enumeration value="XBD"/>
			<xs:enumeration value="XCD"/>
			<xs:enumeration value="XDR"/>
			<xs:enumeration value="XOF"/>
			<xs:enumeration value="XPD"/>
			<xs:enumeration value="XPF"/>
			<xs:enumeration value="XPT"/>
			<xs:enumeration value="XSU"/>
			<xs:enumeration value="XTS"/>
			<xs:enumeration value="XUA"/>
			<xs:enumeration value="XXX"/>
			<xs:enumeration value="YER"/>
			<xs:enumeration value="ZAR"/>
			<xs:enumeration value="ZMW"/>
			<xs:enumeration value="ZWL"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_TipoDeComprobante">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="I"/>
			<xs:enumeration value="E"/>
			<xs:enumeration value="T"/>
			<xs:enumeration value="N"/>
			<xs:enumeration value="P"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_Exportacion">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="01"/>
			<xs:enumeration value="02"/>
			<xs:enumeration value="03"/>
			<xs:enumeration value="04"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_MetodoPago">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="PUE"/>
			<xs:enumeration value="PPD"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_Periodicidad">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="01"/>
			<xs:enumeration value="02"/>
			<xs:enumeration value="03"/>
			<xs:enumeration value="04"/>
			<xs:enumeration value="05"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_Meses">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="01"/>
			<xs:enumeration value="02"/>
			<xs:enumeration value="03"/>
			<xs:enumeration value="04"/>
			<xs:enumeration value="05"/>
			<xs:enumeration value="06"/>
			<xs:enumeration value="07"/>
			<xs:enumeration value="08"/>
			<xs:enumeration value="09"/>
			<xs:enumeration value="10"/>
			<xs:enumeration value="11"/>
			<xs:enumeration value="12"/>
			<xs:enumeration value="13"/>
			<xs:enumeration value="14"/>
			<xs:enumeration value="15"/>
			<xs:enumeration value="16"/>
			<xs:enumeration value="17"/>
			<xs:enumeration value="18"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_TipoRelacion">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="01"/>
			<xs:enumeration value="02"/>
			<xs:enumeration value="03"/>
			<xs:enumeration value="04"/>
			<xs:enumeration value="05"/>
			<xs:enumeration value="06"/>
			<xs:enumeration value="07"/>
			<xs:enumeration value="08"/>
			<xs:enumeration value="09"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_RegimenFiscal">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="601"/>
			<xs:enumeration value="603"/>
			<xs:enumeration value="605"/>
			<xs:enumeration value="606"/>
			<xs:enumeration value="607"/>
			<xs:enumeration value="608"/>
			<xs:enumeration value="609"/>
			<xs:enumeration value="610"/>
			<xs:enumeration value="611"/>
			<xs:enumeration value="612"/>
			<xs:enumeration value="614"/>
			<xs:enumeration value="615"/>
			<xs:enumeration value="616"/>
			<xs:enumeration value="620"/>
			<xs:enumeration value="621"/>
			<xs:enumeration value="622"/>
			<xs:enumeration value="623"/>
			<xs:enumeration value="624"/>
			<xs:enumeration value="625"/>
			<xs:enumeration value="626"/>
			<xs:enumeration value="628"/>
			<xs:enumeration value="629"/>
			<xs:enumeration value="630"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_Pais">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="AFG"/>
			<xs:enumeration value="ALA"/>
			<xs:enumeration value="ALB"/>
			<xs:enumeration value="DEU"/>
			<xs:enumeration value="AND"/>
			<xs:enumeration value="AGO"/>
			<xs:enumeration value="AIA"/>
			<xs:enumeration value="ATA"/>
			<xs:enumeration value="ATG"/>
			<xs:enumeration value="SAU"/>
			<xs:enumeration value="DZA"/>
			<xs:enumeration value="ARG"/>
			<xs:enumeration value="ARM"/>
			<xs:enumeration value="ABW"/>
			<xs:enumeration value="AUS"/>
			<xs:enumeration value="AUT"/>
			<xs:enumeration value="AZE"/>
			<xs:enumeration value="BHS"/>
			<xs:enumeration value="BGD"/>
			<xs:enumeration value="BRB"/>
			<xs:enumeration value="BHR"/>
			<xs:enumeration value="BEL"/>
			<xs:enumeration value="BLZ"/>
			<xs:enumeration value="BEN"/>
			<xs:enumeration value="BMU"/>
			<xs:enumeration value="BLR"/>
			<xs:enumeration value="MMR"/>
			<xs:enumeration value="BOL"/>
			<xs:enumeration value="BIH"/>
			<xs:enumeration value="BWA"/>
			<xs:enumeration value="BRA"/>
			<xs:enumeration value="BRN"/>
			<xs:enumeration value="BGR"/>
			<xs:enumeration value="BFA"/>
			<xs:enumeration value="BDI"/>
			<xs:enumeration value="BTN"/>
			<xs:enumeration value="CPV"/>
			<xs:enumeration value="KHM"/>
			<xs:enumeration value="CMR"/>
			<xs:enumeration value="CAN"/>
			<xs:enumeration value="QAT"/>
			<xs:enumeration value="BES"/>
			<xs:enumeration value="TCD"/>
			<xs:enumeration value="CHL"/>
			<xs:enumeration value="CHN"/>
			<xs:enumeration value="CYP"/>
			<xs:enumeration value="COL"/>
			<xs:enumeration value="COM"/>
			<xs:enumeration value="PRK"/>
			<xs:enumeration value="KOR"/>
			<xs:enumeration value="CIV"/>
			<xs:enumeration value="CRI"/>
			<xs:enumeration value="HRV"/>
			<xs:enumeration value="CUB"/>
			<xs:enumeration value="CUW"/>
			<xs:enumeration value="DNK"/>
			<xs:enumeration value="DMA"/>
			<xs:enumeration value="ECU"/>
			<xs:enumeration value="EGY"/>
			<xs:enumeration value="SLV"/>
			<xs:enumeration value="ARE"/>
			<xs:enumeration value="ERI"/>
			<xs:enumeration value="SVK"/>
			<xs:enumeration value="SVN"/>
			<xs:enumeration value="ESP"/>
			<xs:enumeration value="USA"/>
			<xs:enumeration value="EST"/>
			<xs:enumeration value="ETH"/>
			<xs:enumeration value="PHL"/>
			<xs:enumeration value="FIN"/>
			<xs:enumeration value="FJI"/>
			<xs:enumeration value="FRA"/>
			<xs:enumeration value="GAB"/>
			<xs:enumeration value="GMB"/>
			<xs:enumeration value="GEO"/>
			<xs:enumeration value="GHA"/>
			<xs:enumeration value="GIB"/>
			<xs:enumeration value="GRD"/>
			<xs:enumeration value="GRC"/>
			<xs:enumeration value="GRL"/>
			<xs:enumeration value="GLP"/>
			<xs:enumeration value="GUM"/>
			<xs:enumeration value="GTM"/>
			<xs:enumeration value="GUF"/>
			<xs:enumeration value="GGY"/>
			<xs:enumeration value="GIN"/>
			<xs:enumeration value="GNB"/>
			<xs:enumeration value="GNQ"/>
			<xs:enumeration value="GUY"/>
			<xs:enumeration value="HTI"/>
			<xs:enumeration value="HND"/>
			<xs:enumeration value="HKG"/>
			<xs:enumeration value="HUN"/>
			<xs:enumeration value="IND"/>
			<xs:enumeration value="IDN"/>
			<xs:enumeration value="IRQ"/>
			<xs:enumeration value="IRN"/>
			<xs:enumeration value="IRL"/>
			<xs:enumeration value="BVT"/>
			<xs:enumeration value="IMN"/>
			<xs:enumeration value="CXR"/>
			<xs:enumeration value="NFK"/>
			<xs:enumeration value="ISL"/>
			<xs:enumeration value="CYM"/>
			<xs:enumeration value="CCK"/>
			<xs:enumeration value="COK"/>
			<xs:enumeration value="FRO"/>
			<xs:enumeration value="SGS"/>
			<xs:enumeration value="HMD"/>
			<xs:enumeration value="FLK"/>
			<xs:enumeration value="MNP"/>
			<xs:enumeration value="MHL"/>
			<xs:enumeration value="PCN"/>
			<xs:enumeration value="SLB"/>
			<xs:enumeration value="TCA"/>
			<xs:enumeration value="UMI"/>
			<xs:enumeration value="VGB"/>
			<xs:enumeration value="VIR"/>
			<xs:enumeration value="ISR"/>
			<xs:enumeration value="ITA"/>
			<xs:enumeration value="JAM"/>
			<xs:enumeration value="JPN"/>
			<xs:enumeration value="JEY"/>
			<xs:enumeration value="JOR"/>
			<xs:enumeration value="KAZ"/>
			<xs:enumeration value="KEN"/>
			<xs:enumeration value="KGZ"/>
			<xs:enumeration value="KIR"/>
			<xs:enumeration value="KWT"/>
			<xs:enumeration value="LAO"/>
			<xs:enumeration value="LSO"/>
			<xs:enumeration value="LVA"/>
			<xs:enumeration value="LBN"/>
			<xs:enumeration value="LBR"/>
			<xs:enumeration value="LBY"/>
			<xs:enumeration value="LIE"/>
			<xs:enumeration value="LTU"/>
			<xs:enumeration value="LUX"/>
			<xs:enumeration value="MAC"/>
			<xs:enumeration value="MDG"/>
			<xs:enumeration value="MYS"/>
			<xs:enumeration value="MWI"/>
			<xs:enumeration value="MDV"/>
			<xs:enumeration value="MLI"/>
			<xs:enumeration value="MLT"/>
			<xs:enumeration value="MAR"/>
			<xs:enumeration value="MTQ"/>
			<xs:enumeration value="MUS"/>
			<xs:enumeration value="MRT"/>
			<xs:enumeration value="MYT"/>
			<xs:enumeration value="MEX"/>
			<xs:enumeration value="FSM"/>
			<xs:enumeration value="MDA"/>
			<xs:enumeration value="MCO"/>
			<xs:enumeration value="MNG"/>
			<xs:enumeration value="MNE"/>
			<xs:enumeration value="MSR"/>
			<xs:enumeration value="MOZ"/>
			<xs:enumeration value="NAM"/>
			<xs:enumeration value="NRU"/>
			<xs:enumeration value="NPL"/>
			<xs:enumeration value="NIC"/>
			<xs:enumeration value="NER"/>
			<xs:enumeration value="NGA"/>
			<xs:enumeration value="NIU"/>
			<xs:enumeration value="NOR"/>
			<xs:enumeration value="NCL"/>
			<xs:enumeration value="NZL"/>
			<xs:enumeration value="OMN"/>
			<xs:enumeration value="NLD"/>
			<xs:enumeration value="PAK"/>
			<xs:enumeration value="PLW"/>
			<xs:enumeration value="PSE"/>
			<xs:enumeration value="PAN"/>
			<xs:enumeration value="PNG"/>
			<xs:enumeration value="PRY"/>
			<xs:enumeration value="PER"/>
			<xs:enumeration value="PYF"/>
			<xs:enumeration value="POL"/>
			<xs:enumeration value="PRT"/>
			<xs:enumeration value="PRI"/>
			<xs:enumeration value="GBR"/>
			<xs:enumeration value="CAF"/>
			<xs:enumeration value="CZE"/>
			<xs:enumeration value="MKD"/>
			<xs:enumeration value="COG"/>
			<xs:enumeration value="COD"/>
			<xs:enumeration value="DOM"/>
			<xs:enumeration value="REU"/>
			<xs:enumeration value="RWA"/>
			<xs:enumeration value="ROU"/>
			<xs:enumeration value="RUS"/>
			<xs:enumeration value="ESH"/>
			<xs:enumeration value="WSM"/>
			<xs:enumeration value="ASM"/>
			<xs:enumeration value="BLM"/>
			<xs:enumeration value="KNA"/>
			<xs:enumeration value="SMR"/>
			<xs:enumeration value="MAF"/>
			<xs:enumeration value="SPM"/>
			<xs:enumeration value="VCT"/>
			<xs:enumeration value="SHN"/>
			<xs:enumeration value="LCA"/>
			<xs:enumeration value="STP"/>
			<xs:enumeration value="SEN"/>
			<xs:enumeration value="SRB"/>
			<xs:enumeration value="SYC"/>
			<xs:enumeration value="SLE"/>
			<xs:enumeration value="SGP"/>
			<xs:enumeration value="SXM"/>
			<xs:enumeration value="SYR"/>
			<xs:enumeration value="SOM"/>
			<xs:enumeration value="LKA"/>
			<xs:enumeration value="SWZ"/>
			<xs:enumeration value="ZAF"/>
			<xs:enumeration value="SDN"/>
			<xs:enumeration value="SSD"/>
			<xs:enumeration value="SWE"/>
			<xs:enumeration value="CHE"/>
			<xs:enumeration value="SUR"/>
			<xs:enumeration value="SJM"/>
			<xs:enumeration value="THA"/>
			<xs:enumeration value="TWN"/>
			<xs:enumeration value="TZA"/>
			<xs:enumeration value="TJK"/>
			<xs:enumeration value="IOT"/>
			<xs:enumeration value="ATF"/>
			<xs:enumeration value="TLS"/>
			<xs:enumeration value="TGO"/>
			<xs:enumeration value="TKL"/>
			<xs:enumeration value="TON"/>
			<xs:enumeration value="TTO"/>
			<xs:enumeration value="TUN"/>
			<xs:enumeration value="TKM"/>
			<xs:enumeration value="TUR"/>
			<xs:enumeration value="TUV"/>
			<xs:enumeration value="UKR"/>
			<xs:enumeration value="UGA"/>
			<xs:enumeration value="URY"/>
			<xs:enumeration value="UZB"/>
			<xs:enumeration value="VUT"/>
			<xs:enumeration value="VAT"/>
			<xs:enumeration value="VEN"/>
			<xs:enumeration value="VNM"/>
			<xs:enumeration value="WLF"/>
			<xs:enumeration value="YEM"/>
			<xs:enumeration value="DJI"/>
			<xs:enumeration value="ZMB"/>
			<xs:enumeration value="ZWE"/>
			<xs:enumeration value="ZZZ"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_UsoCFDI">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="G01"/>
			<xs:enumeration value="G02"/>
			<xs:enumeration value="G03"/>
			<xs:enumeration value="I01"/>
			<xs:enumeration value="I02"/>
			<xs:enumeration value="I03"/>
			<xs:enumeration value="I04"/>
			<xs:enumeration value="I05"/>
			<xs:enumeration value="I06"/>
			<xs:enumeration value="I07"/>
			<xs:enumeration value="I08"/>
			<xs:enumeration value="D01"/>
			<xs:enumeration value="D02"/>
			<xs:enumeration value="D03"/>
			<xs:enumeration value="D04"/>
			<xs:enumeration value="D05"/>
			<xs:enumeration value="D06"/>
			<xs:enumeration value="D07"/>
			<xs:enumeration value="D08"/>
			<xs:enumeration value="D09"/>
			<xs:enumeration value="D10"/>
			<xs:enumeration value="P01"/>
			<xs:enumeration value="S01"/>
			<xs:enumeration value="CP01"/>
			<xs:enumeration value="CN01"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_ObjetoImp">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="01"/>
			<xs:enumeration value="02"/>
			<xs:enumeration value="03"/>
			<xs:enumeration value="04"/>
			<xs:enumeration value="05"/>
			<xs:enumeration value="06"/>
			<xs:enumeration value="07"/>
			<xs:enumeration value="08"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_Impuesto">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="001"/>
			<xs:enumeration value="002"/>
			<xs:enumeration value="003"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_TipoFactor">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="Tasa"/>
			<xs:enumeration value="Cuota"/>
			<xs:enumeration value="Exento"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_Estado">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="AGU"/>
			<xs:enumeration value="BCN"/>
			<xs:enumeration value="BCS"/>
			<xs:enumeration value="CAM"/>
			<xs:enumeration value="CHP"/>
			<xs:enumeration value="CHH"/>
			<xs:enumeration value="COA"/>
			<xs:enumeration value="COL"/>
			<xs:enumeration value="DIF"/>
			<xs:enumeration value="CMX"/>
			<xs:enumeration value="DUR"/>
			<xs:enumeration value="GUA"/>
			<xs:enumeration value="GRO"/>
			<xs:enumeration value="HID"/>
			<xs:enumeration value="JAL"/>
			<xs:enumeration value="MEX"/>
			<xs:enumeration value="MIC"/>
			<xs:enumeration value="MOR"/>
			<xs:enumeration value="NAY"/>
			<xs:enumeration value="NLE"/>
			<xs:enumeration value="OAX"/>
			<xs:enumeration value="PUE"/>
			<xs:enumeration value="QUE"/>
			<xs:enumeration value="ROO"/>
			<xs:enumeration value="SLP"/>
			<xs:enumeration value="SIN"/>
			<xs:enumeration value="SON"/>
			<xs:enumeration value="TAB"/>
			<xs:enumeration value="TAM"/>
			<xs:enumeration value="TLA"/>
			<xs:enumeration value="VER"/>
			<xs:enumeration value="YUC"/>
			<xs:enumeration value="ZAC"/>
			<xs:enumeration value="AL"/>
			<xs:enumeration value="AK"/>
			<xs:enumeration value="AZ"/>
			<xs:enumeration value="AR"/>
			<xs:enumeration value="CA"/>
			<xs:enumeration value="NC"/>
			<xs:enumeration value="SC"/>
			<xs:enumeration value="CO"/>
			<xs:enumeration value="CT"/>
			<xs:enumeration value="ND"/>
			<xs:enumeration value="SD"/>
			<xs:enumeration value="DE"/>
			<xs:enumeration value="FL"/>
			<xs:enumeration value="GA"/>
			<xs:enumeration value="HI"/>
			<xs:enumeration value="ID"/>
			<xs:enumeration value="IL"/>
			<xs:enumeration value="IN"/>
			<xs:enumeration value="IA"/>
			<xs:enumeration value="KS"/>
			<xs:enumeration value="KY"/>
			<xs:enumeration value="LA"/>
			<xs:enumeration value="ME"/>
			<xs:enumeration value="MD"/>
			<xs:enumeration value="MA"/>
			<xs:enumeration value="MI"/>
			<xs:enumeration value="MN"/>
			<xs:enumeration value="MS"/>
			<xs:enumeration value="MO"/>
			<xs:enumeration value="MT"/>
			<xs:enumeration value="NE"/>
			<xs:enumeration value="NV"/>
			<xs:enumeration value="NJ"/>
			<xs:enumeration value="NY"/>
			<xs:enumeration value="NH"/>
			<xs:enumeration value="NM"/>
			<xs:enumeration value="OH"/>
			<xs:enumeration value="OK"/>
			<xs:enumeration value="OR"/>
			<xs:enumeration value="PA"/>
			<xs:enumeration value="RI"/>
			<xs:enumeration value="TN"/>
			<xs:enumeration value="TX"/>
			<xs:enumeration value="UT"/>
			<xs:enumeration value="VT"/>
			<xs:enumeration value="VA"/>
			<xs:enumeration value="WV"/>
			<xs:enumeration value="WA"/>
			<xs:enumeration value="WI"/>
			<xs:enumeration value="WY"/>
			<xs:enumeration value="ON"/>
			<xs:enumeration value="QC"/>
			<xs:enumeration value="NS"/>
			<xs:enumeration value="NB"/>
			<xs:enumeration value="MB"/>
			<xs:enumeration value="BC"/>
			<xs:enumeration value="PE"/>
			<xs:enumeration value="SK"/>
			<xs:enumeration value="AB"/>
			<xs:enumeration value="NL"/>
			<xs:enumeration value="NT"/>
			<xs:enumeration value="YT"/>
			<xs:enumeration value="UN"/>
		</xs:restriction>
	</xs:simpleType>
<xs:simpleType name="c_Localidad">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="01"/>
			<xs:enumeration value="02"/>
			<xs:enumeration value="03"/>
			<xs:enumeration value="04"/>
			<xs:enumeration value="05"/>
			<xs:enumeration value="06"/>
			<xs:enumeration value="07"/>
			<xs:enumeration value="08"/>
			<xs:enumeration value="09"/>
			<xs:enumeration value="10"/>
			<xs:enumeration value="11"/>
			<xs:enumeration value="12"/>
			<xs:enumeration value="13"/>
			<xs:enumeration value="14"/>
			<xs:enumeration value="15"/>
			<xs:enumeration value="16"/>
			<xs:enumeration value="17"/>
			<xs:enumeration value="18"/>
			<xs:enumeration value="19"/>
			<xs:enumeration value="20"/>
			<xs:enumeration value="21"/>
			<xs:enumeration value="22"/>
			<xs:enumeration value="23"/>
			<xs:enumeration value="24"/>
			<xs:enumeration value="25"/>
			<xs:enumeration value="26"/>
			<xs:enumeration value="27"/>
			<xs:enumeration value="28"/>
			<xs:enumeration value="29"/>
			<xs:enumeration value="30"/>
			<xs:enumeration value="31"/>
			<xs:enumeration value="32"/>
			<xs:enumeration value="33"/>
			<xs:enumeration value="34"/>
			<xs:enumeration value="35"/>
			<xs:enumeration value="36"/>
			<xs:enumeration value="37"/>
			<xs:enumeration value="38"/>
			<xs:enumeration value="39"/>
			<xs:enumeration value="40"/>
			<xs:enumeration value="41"/>
			<xs:enumeration value="42"/>
			<xs:enumeration value="43"/>
			<xs:enumeration value="44"/>
			<xs:enumeration value="45"/>
			<xs:enumeration value="46"/>
			<xs:enumeration value="47"/>
			<xs:enumeration value="48"/>
			<xs:enumeration value="49"/>
			<xs:enumeration value="50"/>
			<xs:enumeration value="51"/>
			<xs:enumeration value="52"/>
			<xs:enumeration value="53"/>
			<xs:enumeration value="54"/>
			<xs:enumeration value="55"/>
			<xs:enumeration value="56"/>
			<xs:enumeration value="57"/>
			<xs:enumeration value="58"/>
			<xs:enumeration value="59"/>
			<xs:enumeration value="60"/>
			<xs:enumeration value="61"/>
			<xs:enumeration value="62"/>
			<xs:enumeration value="66"/>
			<xs:enumeration value="67"/>
			<xs:enumeration value="68"/>
			<xs:enumeration value="69"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
